### ISSUE TITLE
Have a dinamically size expander

### ISSUE THREAD

**Issue by BanCrash** [MCC321-QC/eMixedNiteMC#10]
**Is your feature request related to a problem? Please describe.**
Hi, with the new expander (not sure what is changed tbh) there are sections that have a lot of blank spaces:
![image](https://user-images.githubusercontent.com/11770760/173185305-571258f9-2dbe-414e-b587-46fed9a864ff.png)
![image](https://user-images.githubusercontent.com/11770760/173185310-15184cb6-940c-4f51-a0d3-31807ae92ade.png)

**Describe the solution you'd like**
A dinamically expander that adapts to the real size, so the expander size that you set in settings with act as the maximum height instead of the height. So if your section has 300 pixels and the maximum expander is set to 350, the expander will get stretched to 300, but if the section has 360 pixels the expander will still have 350 since it's the selected size.

**Describe alternatives you've considered**
Expand the section to fill all the expander, but that caused in the past some sections to not fit well on the expander and I assume that's the reason of this change.

**Additional context**
Idea: With the same expander height set, the expander will be like this:
![image](https://user-images.githubusercontent.com/11770760/173185452-ed1c4d4a-e67f-4e16-affe-f706f8807f81.png)

So when you see achievements the expander will have the size of the left, and when you see game activities the size of the right. But always keeping the maximum value set.

**Comment by MCC321-QC** [comment]
Its a good idea, I remember I wanted it that way when I was working on v3.0 but cant remember what went wrong but instead I integrated most plugin settings so you can control the height and the visibilty among other things directly from the Add-ons menu (F9) in playnite. Every settings I use that you need should be [here](https://github.com/MCC321-QC/eMixedNiteMC/wiki/eMixedNiteMC-Settings). That way there is no blank space (apart for HLTB tab, this one need to be reworked) because every plugin integrated view in those tab can have there heigt adjusted to fit the height of the expander that you have set in the constant menu.

I plan to do an update during the christmas holiday, I'll see what I can do to make the expander adjust his height depending of the content in it.

**Comment by BanCrash** [comment]
> Its a good idea, I remember I wanted it that way when I was working on v3.0 but cant remember what went wrong but instead I integrated most plugin settings so you can control the height and the visibilty among other things directly from the Add-ons menu (F9) in playnite. Every settings I use that you need should be [here](https://github.com/MCC321-QC/eMixedNiteMC/wiki/eMixedNiteMC-Settings). That way there is no blank space (apart for HLTB tab, this one need to be reworked) because every plugin integrated view in those tab can have there heigt adjusted to fit the height of the expander that you have set in the constant menu.
> 
> I plan to do an update during the christmas holiday, I'll see what I can do to make the expander adjust his height depending of the content in it.

I used the settings you provided and this is looking better indeed. However, I don't know how to set the height of the cronology:

![imagen](https://user-images.githubusercontent.com/11770760/201882843-5ec84292-a47e-42f2-95ff-355752154b2a.png)

As you can see it's cutted below, but I searched for the menus and didn't see where to modify it.

**Comment by MCC321-QC** [comment]
The setting you would need here is this one
![SuccessStory settings](https://i.imgur.com/f0oxsvW.png)

It will have to wait for the next update (In the next few weeks) for the dynamic expander, It was a long process updating the api from 2.10 to 2.4.0 and did not have enough time to work on it.

**Comment by BanCrash** [comment]
> The setting you would need here is this one ![SuccessStory settings](https://camo.githubusercontent.com/9ce8420290e4c098fefb738339ccae8915c440bcd43e07ecfc2b2073f4c9a921/68747470733a2f2f692e696d6775722e636f6d2f66306f787376572e706e67)
> 

Ahh, I didn't know that was part of sucessStory, thanks!.

> It will have to wait for the next update (In the next few weeks) for the dynamic expander, It was a long process updating the api from 2.10 to 2.4.0 and did not have enough time to work on it.

Sure, no worries, thanks for this update!

**Comment by MCC321-QC** [comment]
Done in [update 3.6](https://github.com/MCC321-QC/eMixedNiteMC/commit/aea4ff10f40340397662c5f00e855e5a7933f125). The update will be released soon!
