### ISSUE TITLE
GameActivity custom actions dropdown are not being showed

### ISSUE THREAD

**Issue by BanCrash** [MCC321-QC/eMixedNiteMC#12]
**Describe the bug**
Hi, with the last update of GameActivity, there added a feature for adding custom game actions on each activity. For some reason, in eMixedNiteMC are not being showed well on the dropdown.

**To Reproduce**
1. Open GameActivity for a game.
2. Edit one individual entry.
3. Create a new play action.
4. Open the dropdown and see that the actions are not being showed

**Expected behavior**
The options of the dropdown should be showed properly.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/11770760/194751661-b832221d-ebb9-4d56-adde-f68f9df08fdd.png)

For reference, this is the default playnite theme:
![imagen](https://user-images.githubusercontent.com/11770760/194751714-bf1df118-efab-42d5-8227-fd5bca836ac7.png)

Also, with Helium:
![imagen](https://user-images.githubusercontent.com/11770760/194751767-58d7fe32-d98f-4531-a685-3276763ea6cb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Playnite 10 and last eMixedNiteMC

**Comment by MCC321-QC** [comment]
I did not see that one, I will try to fix it in next update, during the Christmas holidays.

**Comment by MCC321-QC** [comment]
Fixed in [v3.5](https://github.com/MCC321-QC/eMixedNiteMC/commit/e51a7105309a45481a75cb499178df2073d5815e)!

**Comment by BanCrash** [comment]
> Fixed in [v3.5](https://github.com/MCC321-QC/eMixedNiteMC/commit/e51a7105309a45481a75cb499178df2073d5815e)!

Perfect, thanks!
