### ISSUE TITLE
Some platform banners not showing

### ISSUE THREAD

**Issue by arshesney** [MCC321-QC/eMixedNiteMC#14]
Some platform banners are not showing up in details view, can't determine how to correctly name them.

Theone I've tested the most is for Amiga: there's one provided in PlatformDefaults, but doesn't appear. I've tried adding a custom one using these names:
- Amiga.png
- Commodore Amiga.png
- Commodore_Amiga.png
- CommodoreAmiga.png

and all lowercase variants, but none worked.

The issue is also present for other platforms like Sega NAOMI, Neo Geo AES and ScuumVM.

The platforms I've assigned the various games to are:
- Commodore Amiga
- Sega NAOMI
- Sega NAOMI 2
- Neo Geo AES
- ScuumVM

Theme is version 3.1, LanguagePack 1.7 and Playnite is 10.3

**Comment by MCC321-QC** [comment]
Im pretty sure its the naming that is at fault here as the other platforms banner work. I will check the name of every banner too make sure there are named correctly with the "official name" of the platform. The thing is its the platform name that is being taken to check is there is a banner available. You should name the banner you want to add the exact same thing as you named it, with space and all.

So for next update (planned during the Christmas holidays) I will check the name and rename if needed all banners and put a list of all the platform natively supported with their exact name in the wiki. The wiki will also be updated with in depth information reguarding the settings and on how to use the theme.

Another thing is ExtraPlatform and Stores folder are where you want to add any platform&source banner. In these 2 folder, the banner need to be named exactly the same as its shown in playnite. Banners from the PlatformDefault folder are loaded from their platform ID as their name are there by default in playnite.

**Comment by MCC321-QC** [comment]
Fixed with [v3.5](https://github.com/MCC321-QC/eMixedNiteMC/commit/e51a7105309a45481a75cb499178df2073d5815e)
