### ISSUE TITLE
Playnite Sounds integration

### ISSUE THREAD

**Issue by Mellified** [MCC321-QC/eMixedNiteMC#15]
So I've taken to using [Playnite Sounds](https://playnite.link/forum/thread-432.html) rather than the video trailer audio. The soundtracks are much nicer to hear versus the sometimes obnoxious audio from the trailers.

Unfortunately the combination of muted video and soundtracks is clunky in eMixedNiteMC today. Ideally the theme would link the playback of video and the music playback so that stopping one would stop the other. Since Playnite Sounds also supports multiple tracks it'd be nice to see which soundtrack is playing somewhere... maybe as transparent text over the video window.

**Comment by MCC321-QC** [comment]
Nice idea, I like it! But unfortunatly, I dont see aything related to theme integration in Playnite Sounds [Github](https://github.com/joyrider3774/PlayniteSound), so I dont think there is a way to show a list of soundtracks or make the video and soudtrack stop at the same time.

For the clunky part, you will need to be a little more specific. I understand that you play a soudtrack and mute the video but I dont understand what you mean by clunky.

**Comment by Mellified** [comment]
Since there are no controls for the soundtrack it makes it impossible to mute. Using the eMixedNiteMC video controls don't work obviously.

**Comment by xCeeTee** [comment]
> Since there are no controls for the soundtrack it makes it impossible to mute. Using the eMixedNiteMC video controls don't work obviously.

I'm trying to replicate this on my end to see if I can help. I get controls popup for me, including a volume slider. The thing is, whilst trying to pause the trailer, I notice I'm only getting the controls for Playnite Sounds. I do remember when I reinstalled back in the summer I installed PS before the plugin that has the trailer support. I have a feeling like Playnite may only be able to show one of these at a time, but I'm no expert.

**Comment by MCC321-QC** [comment]
It will have to be for the next update (in the next few weeks), v3.5 took more time than anticipated and I did not have enough time to work on it.

**Comment by MCC321-QC** [comment]
Found this [issue](https://github.com/joyrider3774/PlayniteSound/issues/40) about this.

**Comment by MCC321-QC** [comment]
Finally done in [version 3.75](https://github.com/MCC321-QC/eMixedNiteMC/commit/a314defb20d68ab28dbe47ba1437423a69dbf6fe). Update will be released this weekend! I added the play/pause control and the name of the currently playing song + an option to toggle visibility in [ThemeModifier](https://github.com/Lacro59/playnite-thememodifier-plugin)

Here a little preview!
The control are located in the bottom right corner of the window so it will stay there even when scrolling.
![eMixedNiteMC_Playnite_Sound_Mod_Integration_Preview](https://github.com/user-attachments/assets/42a79aea-8764-4268-94cc-74ac3d8fc5bd)
