### ISSUE TITLE
Missing banner for EA app.

### ISSUE THREAD

**Issue by blackparadox** [MCC321-QC/eMixedNiteMC#16]
The built in Origin library importer has been renamed to be the "EA app", along with the default "Source" value.

As such, any new EA/Origin apps are not getting the Origin banner applied.

If anyone needs a hotfix - copy/paste "Images/Banners/Stores/Origin.png" to "Images/Banners/Stores/EA App.png".

Or alternatively create your own banner and drop it in that location.

I've attached my banner in case anyone wants to use it, but felt a pull request was a bit overkill (as you guys might not like it/have a specific art style etc).

![EA App](https://user-images.githubusercontent.com/3729276/204002841-0e0524ff-48e2-4490-b935-62acf34cb34c.png)

**Comment by MCC321-QC** [comment]
Thank you for the banner, I included it in [v3.5](https://github.com/MCC321-QC/eMixedNiteMC/commit/e51a7105309a45481a75cb499178df2073d5815e)!
