### ISSUE TITLE
Add a setting to show playtime count on grid view

### ISSUE THREAD

**Issue by BanCrash** [MCC321-QC/eMixedNiteMC#2]
**Is your feature request related to a problem? Please describe.**
It's not a problem, I just want an improvement. I want to see playtime count on grid view without entering a game. This maybe could be enable or disable on theme settings.

**Describe the solution you'd like**
Adding the playtime count in grid view placing it after "Status".

**Describe alternatives you've considered**
I can't think of another, I think this is the proper place to place it.

**Additional context**
Actual:
![image](https://user-images.githubusercontent.com/11770760/163133628-7c4aa54f-6892-4560-85ea-b764314ca881.png)
My idea (sorry for using paint):
![image](https://user-images.githubusercontent.com/11770760/163133840-a59d4338-141f-41dd-a219-b596f6e9fc04.png)
Obviously it should has its icon, and should be more space. It's just for showing the idea.

**Comment by MCC321-QC** [comment]
I like the Idea, It should be added soon.

**Comment by MCC321-QC** [comment]
Fixed in version [2.80](https://github.com/MCC321-QC/eMixedNiteMC/commit/ce132ee3ca37ec00f3653fd6b0f4783c358ef130)

**Comment by BanCrash** [comment]
> Done in version [2.80](https://github.com/MCC321-QC/eMixedNiteMC/commit/ce132ee3ca37ec00f3653fd6b0f4783c358ef130), setting is disable by default. Can be enable in constant menu of [ThemeModifier](https://github.com/Lacro59/playnite-thememodifier-plugin).

Perfect, thank you!
