### ISSUE TITLE
Option to hide title if there's a logo

### ISSUE THREAD

**Issue by Elaborendum** [MCC321-QC/eMixedNiteMC#29]
**Is your feature request related to a problem? Please describe.**
Seeing the same title 3 times can be a bit repetitive (covers usually have the title of the game in them, and the written title and logo title are in roughly the same space). There's currently a setting to hide all logos or hide all titles. But sometimes games don't have any available logos so you can't hide all titles.

**Describe the solution you'd like**
A setting like the regular eMixedNite to hide the written titles in all games that have a downloaded logo.

**Describe alternatives you've considered**
Make a logo for all games that have none and just hide written titles. Or just hide all written titles.

**Additional context**
It seems to be available through ThemeModifier in the regular eMixedNite theme

**Comment by MCC321-QC** [comment]
Was planned for version 3.6 but not enough time. Planned for next update!

**Comment by MCC321-QC** [comment]
Done in [version 3.75](https://github.com/MCC321-QC/eMixedNiteMC/commit/a7a25ed16629ecfddf9fccfa992d68f99d50c26a), the update will be released later today!
