### ISSUE TITLE
Add support for translations

### ISSUE THREAD

**Issue by BanCrash** [MCC321-QC/eMixedNiteMC#3]
**Is your feature request related to a problem? Please describe.**
Currently part of the theme is on english and part on your playnite selected language, this could be solved adding the option to translate using Crowdin.

**Describe the solution you'd like**
Have the option to have the theme on my Playnite selected language (Spanish)

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://user-images.githubusercontent.com/11770760/163167527-698cabb2-1ead-42bb-baf1-986e453e69e0.png)

As you can see some strings are translated and some are on English. I would like to have all in Spanish.

**Comment by MCC321-QC** [comment]
I did not find any way to reference the localization file in a theme so im currently working on a extension that will be used to reference the localization file in eMixedNiteMC. Extension is called "eMixedNiteMC Language Pack" and it should be ready for release in the next few days. I will put the Crowdin link in the [ReadMe.md](https://github.com/MCC321-QC/eMixedNiteMC/blob/main/README.md) and in [Playnite forum](https://playnite.link/forum/thread-801.html) as soon as everything is set up.

**Comment by BanCrash** [comment]
> I did not find any way to reference the localization file in a theme so im currently working on a extension that will be used to reference the localization file in eMixedNiteMC. Extension is called "eMixedNiteMC Language Pack" and it should be ready for release in the next few days. I will put the Crowdin link in the [ReadMe.md](https://github.com/MCC321-QC/eMixedNiteMC/blob/main/README.md) and in [Playnite forum](https://playnite.link/forum/thread-801.html) as soon as everything is set up.

Perfect, thanks! I will start translating into spanish when it's available.

**Comment by MCC321-QC** [comment]
https://github.com/MCC321-QC/eMixedNiteMC-Language-Pack
https://crowdin.com/project/emixednitemc

**Comment by BanCrash** [comment]
> https://github.com/MCC321-QC/eMixedNiteMC-Language-Pack https://crowdin.com/project/emixednitemc

Perfect, I will check it and start the translation into spanish, thanks!
