### ISSUE TITLE
Expandable Link Box

### ISSUE THREAD

**Issue by BLACK4585** [MCC321-QC/eMixedNiteMC#31]
**Is your feature request related to a problem? Please describe.**
When you have a lot of links for a game, because you are using the Link Utilities Plugin, there are often more links than can be shown.

**Describe the solution you'd like**
An extension to the current linkbox. You have a dropdown arrow which expands the box so you can see all the other links. Same design like the box to show steam news, HLTB details etc.

**Describe alternatives you've considered**
Using the burger menu on the game page and hover over the `links` section.

**Comment by MCC321-QC** [comment]
The link panel will now warp and make a second line to show every link. 
Done in [version 3.6](https://github.com/MCC321-QC/eMixedNiteMC/commit/aea4ff10f40340397662c5f00e855e5a7933f125). The update will be released soon!

**Comment by danjiss** [comment]
@MCC321-QC There's a option/code to revert it? I prefer classic version (extra links hiden). Thank you!

**Comment by MCC321-QC** [comment]
> Will this may cause some bugs in v3.6?

@danjiss No it should be all good!

**Comment by MCC321-QC** [comment]
Worked on this in [version 3.75](https://github.com/MCC321-QC/eMixedNiteMC/commit/a7a25ed16629ecfddf9fccfa992d68f99d50c26a) but could not make it work like I wanted, this will wait for next update next week!

**Comment by danjiss** [comment]
It would be great with the option on theme modifier but honestly, is probably something only I care about, so it's not really worth spending time on. Since it doesn't cause any issues, I made the edit xml and it's working perfectly!

Thank you

**Comment by MCC321-QC** [comment]
Ill leave this open because I think its and options worth it since you have access to every link in the option menu of the games. So you could show only the first few links and not the rest if its what you wish when using a small GameView!

**Comment by MCC321-QC** [comment]
I will close the issue but this is still in my todo list!

**Comment by danjiss** [comment]
Last update is awesome! You've done a very great job! I keep adding the line and work perfectly.
Thank you!
