### ISSUE TITLE
Integration for new addons

### ISSUE THREAD

**Issue by BLACK4585** [MCC321-QC/eMixedNiteMC#34]
Hey, I saw some recent activity on this repo which really makes me and I think a lot of other people happy!
Following, I just want to throw in a list of addons, which require Theme support. It would be really nice if they get supported in the future.

- [Back to Game](https://github.com/ashpynov/BackToGame)
- [Game Relations](https://github.com/darklinkpower/PlayniteExtensionsCollection)
- [Play Notes](https://github.com/darklinkpower/PlayniteExtensionsCollection)

Thank you very much in advance!

**Comment by Satanarious** [comment]
Any news on this?

**Comment by BLACK4585** [comment]
I just wrote a bit with @MCC321-QC a while ago and he told me that he's working on new features and bug fixes.
We can expect updates later this year.

**Comment by MCC321-QC** [comment]
Support added for Game Relations and PlayNotes.
Done in [version 3.6](https://github.com/MCC321-QC/eMixedNiteMC/commit/aea4ff10f40340397662c5f00e855e5a7933f125), the update will be released soon!

Support for Back to Game will be there in the near future.

**Comment by MCC321-QC** [comment]
Support for [BackToGame](https://github.com/ashpynov/BackToGame) done in [version 3.75](https://github.com/MCC321-QC/eMixedNiteMC/commit/73751b7314770ee404a310837673ed8a91b74dae), update will be release this weekend!
