### ISSUE TITLE
saving preset

### ISSUE THREAD

**Issue by wigglywag** [MCC321-QC/eMixedNiteMC#4]
**Is your feature request related to a problem? Please describe.**
I really like the idea of being able to customize this theme, but every time I launch Playnite, I'm back on the default preset. Maybe I'm just missing it but it would be nice to have a way to save the theme preset.

**Describe the solution you'd like**
A way to save the way we prefere to customize this theme

**Describe alternatives you've considered**
For now I do it manually on every launch

**Additional context**

**Comment by MCC321-QC** [comment]
You can save your settings in the constant menu of [ThemeModifier](https://github.com/Lacro59/playnite-thememodifier-plugin).
You will find ThemeModifier in the Add-ons menu(F9) of Playnite. 
Check [this post](https://playnite.link/forum/thread-801-post-6767.html#pid6767) on the Playnite forum for more information.
