### ISSUE TITLE
Possibilty to switch to round corners of Playnite window in Windows 11

### ISSUE THREAD

**Issue by lionnesquaer** [MCC321-QC/eMixedNiteMC#48]
### Feature Description

Recently this was removed from theme in ver. 3.75
But personally i much like round corners, maybe we can find a solution that will suit everyone.

**Comment by MCC321-QC** [comment]
Everything worked like a charm, done in [v3.90](https://github.com/MCC321-QC/eMixedNiteMC/commit/a99e7dbb6fef0b05b1c139cc748209fafcd18599)! You will need the plugin [Theme Options](https://github.com/ashpynov/ThemeOptions) to enable this.
