### ISSUE TITLE
Details panel overlapping text

### ISSUE THREAD

**Issue by xCeeTee** [MCC321-QC/eMixedNiteMC#49]
### Bug Description

The text in my details panel is overlapping and some lines are unreadable. It only happened after the last update.

### Screenshots

https://i.imgur.com/xsrG2X6.jpeg

**Comment by MCC321-QC** [comment]
I completely forgot to try the settings that toggle 2 and 1 column on de details panel, I will try to fix this right away!

**Comment by MCC321-QC** [comment]
Done in [v3.90](https://github.com/MCC321-QC/eMixedNiteMC/commit/a99e7dbb6fef0b05b1c139cc748209fafcd18599)! I still have some adjustments to do for the margin when the options for 1 column is enabled but its gonna be for another update.
