### ISSUE TITLE
The source in grid view isn't being correctly shown if the chosen game is a emulated game

### ISSUE THREAD

**Issue by ferrazpedro** [MCC321-QC/eMixedNiteMC#5]
Whenever we choose an emulated game, the source appears like this:
![image](https://user-images.githubusercontent.com/37643357/167435201-f67989ff-6321-45ec-923e-8b0f0cd30636.png)
Since this is a lot diferent from the one in PC games, I do believe this is a bug.
![image](https://user-images.githubusercontent.com/37643357/167435308-8fa77624-74e4-4f30-b13a-6a5cfe50bfe0.png)

**Comment by MCC321-QC** [comment]
This would mean that you did not put a source in the "Source" field in General Tab of the "Edit Game Details" menu.
![image](https://i.imgur.com/9LZIyK8.png)
More info at the end of [this post](https://playnite.link/forum/thread-801-post-6750.html#pid6750).
If you have a lot of game to do dont forget that you can filter and then use "CTRL+A" after clicking a game in the list and then use "F3" to mass edit all currently filtered game.

**Comment by MCC321-QC** [comment]
Done in version [2.80](https://github.com/MCC321-QC/eMixedNiteMC/commit/ce132ee3ca37ec00f3653fd6b0f4783c358ef130).
