### ISSUE TITLE
Blur and faint background image on bottom of trailers.

### ISSUE THREAD

**Issue by STOPchris1** [MCC321-QC/eMixedNiteMC#51]
### Bug Description

All of my videos/trailers have a portion of the bottom blurred. For some games, when playing a trailer I can see part of the background bleeding through the video. Is there an option to fix this?

**Comment by MCC321-QC** [comment]
Could you show me a screenshot? I know exactly what you mean but I'm curious to see which way you personalized your theme so it make your background bleed through your video, for me is very faint, like almost unnoticeable. 

You could try these  2 options in the [ThemeModifier](https://github.com/Lacro59/playnite-thememodifier-plugin) constants menu as these will change the blur effect in the background. Please let me know if those 2 options makes a difference for you. (for the "Bleeding part")<br>
![Screenshot 2024-10-30 042430](https://github.com/user-attachments/assets/8604200a-43d0-40c5-978f-f38c2e2b4f95)

**Comment by STOPchris1** [comment]
If I remove the blur effect by setting "grid view background blur effect height" to max, I get what's in the attached image. Is there a way to get both the trailer and background to cover the same amount of space so that the background image does not show when the trailer is playing?
<img width="748" alt="image" src="https://github.com/user-attachments/assets/5cd699fe-ca72-45c3-ae05-c0b4490a5391">

**Comment by STOPchris1** [comment]
It looks like they are the same size actually, the background image just bleeds through the video at the bottom.

**Comment by STOPchris1** [comment]
I already have that setting disabled in Playnite settings. It doesn't fix the issue with the setting enabled or disabled.

**Comment by MCC321-QC** [comment]
I added a trigger to the background image visibility to be disabled when a video is visible. Done in [v3.95](https://github.com/MCC321-QC/eMixedNiteMC/commit/fbc274c01856044e9c1bada904fd6286d48d130e), the update will be released soon, It should fix this problem!

**Comment by STOPchris1** [comment]
Update v3.95 completely fixed this issue. It looks really good now. I appreciate you working on a fix really fast. Your theme is amazing!

**Comment by MCC321-QC** [comment]
Its my pleasure, thank you!

**Comment by STOPchris1** [comment]
This issue came back in the latest version.
