### ISSUE TITLE
Support for "Details to Grid View Converter" addon

### ISSUE THREAD

**Issue by ScottVordem** [MCC321-QC/eMixedNiteMC#52]
### Feature Description

Darklinkpower's Playnite addon [Details to Grid View Converter](https://playnite.link/addons.html#ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3) allows the Grid View details panel to be converted into the Details View, so all the information from the details view shows up in the grid view details panel.

Not sure how easy it is to implement as I have only seen darklinkpower's own themes use it, but understand if it is not possible.

**Comment by MCC321-QC** [comment]
Im not sure its really necessary because I made both view almost the same way, it would help me if you could tell me which element of the theme you are talking about?

**Comment by ScottVordem** [comment]
It is not a specific element but more of being able to use Theme Modifier to change how the details view looks, so it can be customizable for the grid view details pane. Upon closer inspection, I did not realize that both views are equally customizable with Theme Modifier and both views have the same elements. Forgive me.

**Comment by MCC321-QC** [comment]
Its ok! Im gonna close this seen its been resolved.
