### ISSUE TITLE
There's a dark background behing the Playnite logo

### ISSUE THREAD

**Issue by ferrazpedro** [MCC321-QC/eMixedNiteMC#6]
Like I said in the title, there's a dark square behind the Playnite logo. I do believe this area should be transparent or follow the color used at the time in the theme.
![image](https://user-images.githubusercontent.com/37643357/167436127-5ee8647d-e73c-4194-af6a-28f775e8f85e.png)
![image](https://user-images.githubusercontent.com/37643357/167436352-9a7fc79b-b263-47e3-8080-3fc35c441dc7.png)

**Comment by MCC321-QC** [comment]
You can normally change it in ThemeModifier Constant menu but there is currently a bug that prevent any color of being saved (Still trying to figure out this one). You need to change it directly in the Constants.xaml file in the theme installation directory.

![image](https://i.imgur.com/xP1tHXe.png)

Change these lines, in the file Constants.xaml
`Line 50 and 51`
`<SolidColorBrush x:Key="TopPanelBrush" Color="#FF262626" />`
`<SolidColorBrush x:Key="SideIconBrush" Color="#FF262626" />`
With these lines
`Line 50 and 51`
`<SolidColorBrush x:Key="TopPanelBrush" Color="Transparent" />`
`<SolidColorBrush x:Key="SideIconBrush" Color="Transparent" />`

More info at the end of [this post](https://playnite.link/forum/thread-801-post-8368.html#pid8368).
