### ISSUE TITLE
Divide information in the details pane

### ISSUE THREAD

**Issue by BanCrash** [MCC321-QC/eMixedNiteMC#7]
**Is your feature request related to a problem? Please describe.**
Hi, with the new addition of play count the details pane needs to be huge in order to have all the information about source, play count, etc. I was thinking that giving an option to divide those details in 2 rows would allow users to have a lower details pane.

**Describe the solution you'd like**
Have a setting to change the row of source, last time played etc into 2 rows to have a more compact details pane.

**Describe alternatives you've considered**
That it automatically got divided in the necessary amount of rows according to the width selected, but I think this would be complicated to implement so with the setting of dividing in 2 rows would be just fine.

**Additional context**
Actual pane:
![image](https://user-images.githubusercontent.com/11770760/169071585-9232fb98-fa3f-474f-b0dd-d07ae9701b1f.png)

Idea:
![image](https://user-images.githubusercontent.com/11770760/169071861-2219fc31-8f53-4603-9e5b-ad8e27304f83.png)

**Comment by MCC321-QC** [comment]
Its a good idea, It will be implemented soon!

**Comment by MCC321-QC** [comment]
Done in [v2.85](https://github.com/MCC321-QC/eMixedNiteMC/commit/c40606d5741c1a7200916b0b0072c2da73ca6280)! I integrated the automatic way so no new setting and did it for almost every needed element.
